# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      GOPROXY: https://proxy.golang.org
      GO111MODULE: on
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    name: Go ${{ matrix.os }} with hugo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a set of commands using the runners shell
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'
          extended: true
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run hugo
        run: |
          go version
          pwd
          ls
          hugo version
          hugo -d docs
          git add docs
          git commit -m "$(date)"
          git push wangyijie master
